services:
  wordpress:
    image: syneidon/laravel:php80-nonode
    container_name: ${PROJECT_NAME:-app}_wordpress
    ports:
      - '${HTTP_PORT:-80}:80'
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME:-app}_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME:-app}
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
